server:
  port: 8080
logging:
  level:
    root: info
spring:
  main:
    lazy-initialization: true
  security:
    oauth2:
      client:
        registration:
          myApp:
            client-id: https://danielflorido.github.io/podsModuleRest/src/main/resources/clients/ClientIdDocument.jsonld
            provider: inrupt
            scope:
              - openid
              - webid
            client-authentication-method: none
            authorization-grant-type: authorization_code
        provider:
          inrupt:
            issuer-uri: https://login.inrupt.com
            token-uri: https://login.inrupt.com/token
            authorization-uri: https://login.inrupt.com/authorization
            user-info-uri: https://login.inrupt.com/userinfo
            jwk-set-uri: https://login.inrupt.com/jwks